# Generated by Django 5.2.9 on 2025-12-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(help_text="Icon class name (e.g., 'calculator')", max_length=50)),
                ('overview', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('section_type', models.CharField(choices=[('text', 'Text Block'), ('list', 'List (Bullet Points)'), ('process', 'Process Steps'), ('benefits', 'Benefits (Checkmarks)'), ('tags', 'Tags (Who Can Benefit)')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Main text content')),
                ('items', models.TextField(blank=True, help_text='Enter items separated by newlines (for Lists/Process/Benefits)')),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
