# Generated by Django 5.2.9 on 2025-12-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, help_text="Path to service image (e.g., 'services/estimation.png')", max_length=200),
        ),
    ]
