# Generated by Django 5.2.9 on 2025-12-31 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(help_text="Path to logo (e.g., 'software/autocad.png')", max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='main.service')),
            ],
            options={
                'verbose_name_plural': 'Service Software',
                'ordering': ['order'],
            },
        ),
    ]
