# Generated by Django 5.2.9 on 2026-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicesoftware'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='is_subsection',
            field=models.BooleanField(default=False, help_text='If True, this section will be rendered as a sub-section of the previous block (e.g., inside Overview)'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='items',
            field=models.TextField(blank=True, help_text='List items separated by newlines'),
        ),
    ]
