# Generated by Django 5.2.9 on 2026-01-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_servicefeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSoftware',
        ),
    ]
