# Generated by Django 5.2.9 on 2026-01-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_servicesoftware'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_subtitle', models.CharField(default='ABOUT US', max_length=100)),
                ('deck_heading', models.CharField(default='Building Global Partnerships', max_length=200)),
                ('deck_content_1', models.TextField(blank=True)),
                ('deck_content_2', models.TextField(blank=True)),
                ('vision_heading', models.CharField(default='Shaping the Future Together', max_length=200)),
                ('vision_content', models.TextField(blank=True)),
                ('mission_heading', models.CharField(default='Delivering Excellence in Every Project', max_length=200)),
                ('mission_content', models.TextField(blank=True)),
                ('stat_1_value', models.CharField(default='20+', max_length=50)),
                ('stat_1_label', models.CharField(default='Years of Excellence', max_length=100)),
                ('stat_2_value', models.CharField(default='11.5K', max_length=50)),
                ('stat_2_label', models.CharField(default='Projects Completed', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='CommitmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number', models.CharField(default='01', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_badge', models.CharField(default='EST. 2005', max_length=50)),
                ('visual_heading', models.CharField(default='Design your legacy.', max_length=200)),
                ('visual_image', models.CharField(default='images/contact_illustration.png', max_length=200)),
                ('form_subtitle', models.CharField(default='Get in Touch', max_length=100)),
                ('form_heading', models.CharField(default='Start the Conversation', max_length=200)),
                ('form_description', models.TextField(blank=True, default='Ready to bring your vision to life? Our team of architects and engineers is here to help you every step of the way.')),
                ('response_title', models.CharField(default='24-Hour Response Guarantee', max_length=200)),
                ('response_description', models.TextField(blank=True, default='We typically respond within 24 hours. Most projects have a 24-48 hour turnaround time.')),
            ],
            options={
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Building with Nature's Wisdom", max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Thoughtful construction advancing the balance between sustainability and architectural global innovation.')),
                ('hero_bg_image', models.CharField(default='images/hero_background_dark.png', max_length=200)),
                ('about_heading', models.CharField(default='Building Global Partnerships', max_length=200)),
                ('about_content', models.TextField(blank=True, help_text='HTML allowed')),
                ('services_subtitle', models.CharField(default='Our Services', max_length=100)),
                ('services_heading', models.CharField(default='Comprehensive Solutions for Every Project', max_length=200)),
                ('services_description', models.TextField(blank=True, default='From CAD drafting to interior design, we deliver expert services tailored to your construction and architectural needs.')),
                ('services_bg_image', models.CharField(default='images/services_header_bg.png', max_length=200)),
                ('software_label', models.CharField(default='Toolset', max_length=50)),
                ('software_heading', models.CharField(default='Technical Precision', max_length=200)),
                ('software_description', models.TextField(blank=True, default='Our software stack ensures millimeter-perfect execution.')),
                ('free_sample_heading', models.CharField(default='Get a Free Sample', max_length=200)),
                ('free_sample_description', models.TextField(blank=True, default='Send us your drawings (PDF/DWG) and receive a complimentary sample to evaluate our quality and accuracy.')),
            ],
            options={
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ConstructPro', max_length=100)),
                ('logo', models.CharField(blank=True, help_text='Path to logo image', max_length=200)),
                ('phone_number', models.CharField(default='+1 123 456 7895', max_length=20)),
                ('email', models.EmailField(default='info@constructorpro.com', max_length=254)),
                ('address', models.TextField(default='1234 Builder Lane, Architect City, AC 54321')),
                ('footer_description', models.TextField(blank=True, default="Building with Nature's Wisdom")),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings (Global)',
            },
        ),
        migrations.CreateModel(
            name='SoftwareTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(help_text='Path to logo image', max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Customer', max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(help_text='Paste SVG path or full SVG code here')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order'],
            },
        ),
    ]
