# Generated by Django 5.2.9 on 2026-01-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutgalleryimage_aboutpage_commitmentitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number', models.CharField(default='01', max_length=10)),
                ('icon_svg', models.TextField(help_text='Paste SVG path or full SVG code here')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
