# Generated by Django 5.2.9 on 2026-01-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_processstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='Upload a hero background image', null=True, upload_to='hero_images/'),
        ),
    ]
