# Generated by Django 5.2.9 on 2026-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_homepage_hero_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, choices=[('project', 'New Project Inquiry'), ('career', 'Careers'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='contact_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
