# Generated by Django 5.2.9 on 2026-01-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo image', null=True, upload_to='site_logos/'),
        ),
    ]
