# Generated by Django 5.2.9 on 2026-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_address',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide address on the site'),
        ),
    ]
