# Generated by Django 5.2.9 on 2026-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitesettings_show_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutgalleryimage',
            name='image',
            field=models.ImageField(upload_to='about_gallery/'),
        ),
    ]
