# Generated by Django 5.2.9 on 2026-01-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_aboutgalleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='visual_image',
            field=models.ImageField(default='contact_visuals/contact_illustration.png', upload_to='contact_visuals/'),
        ),
    ]
