# Generated by Django 5.2.9 on 2026-01-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_contactpage_visual_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='services_bg_image',
            field=models.ImageField(default='images/services_header_bg.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text="Path to service image (e.g., 'services/estimation.png')", upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='softwaretool',
            name='image',
            field=models.ImageField(help_text='Path to logo image', upload_to='images/software/'),
        ),
    ]
