# Generated by Django 5.2.9 on 2026-01-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_homepage_services_bg_image_alter_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(help_text="Path to image (e.g., 'services/gallery/1.jpg')", upload_to='services/gallery/'),
        ),
    ]
